name: "Autogenerate"
description: "Generate and publish Dockerfiles and Stackbrew Library files"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 16.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 16.x

    - name: Install dependencies
      shell: bash
      run: |
        npm ci

    # FIXME: remove 'supervisor' from the 'all' target
    - name: Generate Dockerfiles
      shell: bash
      run: |
        npm run os-arch
        npm run os-device
        npm run stack-arch
        npm run stack-device

        tar czf ${{ runner.temp }}/files.tgz -C balena-base-images .

    # https://github.com/actions/upload-artifact
    - name: Upload artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: files-${{ github.event.pull_request.head.sha }}
        path: ${{ runner.temp }}/files.tgz
        retention-days: 90

    # FIXME: remove 'supervisor' from the 'all-lib' target
    - name: Generate Stackbrew Library files
      shell: bash
      run: |
        npm run os-arch-lib
        npm run os-device-lib
        npm run stack-arch-lib
        npm run stack-device-lib

        tar czf ${{ runner.temp }}/libs.tgz -C library .

    # publish these to a github release so they can be downloaded by official-images
    # https://github.com/actions/upload-artifact
    - name: Upload artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: gh-release-${{ github.event.pull_request.head.sha }}
        path: ${{ runner.temp }}/libs.tgz
        retention-days: 90

    # BELOW IS FOR TESTING ONLY, REMOVE BEFORE MERGING

    # https://github.com/dawidd6/action-download-artifact
    - name: Download artifacts from PR workflow
      uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67 # v2
      with:
        # github_token: ${{ steps.github_tokens.outputs.trusted || false }}
        commit: ${{ github.event.pull_request.head.sha }}
        path: ${{ runner.temp }}
        workflow_conclusion: success
        name: files-${{ github.event.pull_request.head.sha }}

    # https://github.com/crazy-max/ghaction-import-gpg
    - name: Import GPG private key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
      with:
        gpg_private_key: ${{ fromJSON(inputs.secrets).GPG_PRIVATE_KEY }}
        passphrase: ${{ fromJSON(inputs.secrets).GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit Dockerfiles
      shell: bash
      id: commit
      env:
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      run: |
        tar xzf ${{ runner.temp }}/files-${{ github.event.pull_request.head.sha }}.tgz -C balena-base-images
        echo "status=$(git status --porcelain balena-base-images)" >> $GITHUB_OUTPUT
        git add balena-base-images
        git commit -m "Autogenerated Dockerfiles" -m "[skip ci]"
