name: "Autogenerate"
description: "Download and commit Dockerfiles"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    # https://oras.land/cli/2_pulling/
    - name: Pull artifacts with ORAS
      shell: bash
      run: |
        oras pull -p ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }} \
          ghcr.io/${{ github.repository }}:files-${{ github.event.pull_request.head.sha }}

    # https://github.com/crazy-max/ghaction-import-gpg
    - name: Import GPG private key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
      with:
        gpg_private_key: ${{ fromJSON(inputs.secrets).GPG_PRIVATE_KEY }}
        passphrase: ${{ fromJSON(inputs.secrets).GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit Dockerfiles
      shell: bash
      id: commit
      env:
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      run: |
        tar xzf ${{ runner.temp }}/files-${{ github.event.pull_request.head.sha }}.tgz -C balena-base-images
        echo "status=$(git status --porcelain balena-base-images)" >> $GITHUB_OUTPUT
        git add balena-base-images
        git commit -m "Autogenerated Dockerfiles" -m "[skip ci]"

    - name: Push commit to base branch
      shell: bash
      if: steps.commit.outputs.status != ''
      run: |
        git push origin HEAD:refs/heads/${{ github.base_ref }}
